### PR TITLE
Fix basic error, Sorry ;-;

### PR DESCRIPTION
**Pull request by RedstoneAlmeida**

### CODE REVIEW

**Comment by Sandertv** [comment]
No problem :P mind if I change some small things in it?

**Comment by RedstoneAlmeida** [comment]
of course, feel free :D

**Comment by Sandertv** [comment]
Thanks for the idea of an API btw :). Once we have a full API I'll rewrite the plugin using it!

**Comment by RedstoneAlmeida** [comment]
Okay :D

**Comment by oGalatico** [comment]
Hi red :)

**Pull request merged**
