### PR TITLE
Not need for clearing, because player needs item to live

### PR DESCRIPTION
**Pull request by Adam1609**

### CODE REVIEW

**Comment by Sandertv** [comment]
Hmmm he would still have the items of the wrong character though...

**Comment by Adam1609** [comment]
I have tested it, teleport to other world don't cause wrong character's item. That's good though :D

**Comment by Sandertv** [comment]
I'll just make it so it only removes the items from classes, not all items.

**Comment by Adam1609** [comment]
Yeah, that could work

**Comment by Driesboy** [comment]
-1 
some plugins will have some bugs with this

**Comment by Sandertv** [comment]
Yeah @Driesboy is right, I'm just going to make a switch in the config to either remove all items, or remove only rpg items.

**Comment by Driesboy** [comment]
Ok

Op 24-okt.-2016 16:59 schreef "Blabla" <notifications@github.com>:

**Pull request closed without merging**
