### PR TITLE
WIP  Allow making unlimited RPG worlds and better performance

### PR DESCRIPTION
**Pull request by Sandertv**
This update adds the ability to make as many RPG worlds as you'd like. This update also cleans up loads of code. It might not be stable, it has yet to be tested.

DO NOT MERGE YET, UNTESTED

### CODE REVIEW

**Comment by Driesboy** [comment]
done?

**Comment by Adam1609** [comment]
I will test it

**Comment by Sandertv** [comment]
+1

**Comment by Driesboy** [comment]
+1

**Comment by Driesboy** [comment]
?

**Comment by Sandertv** [comment]
It was too much of a mess so I quickly pushed it in one commit directly to 1.0-Update

**Comment by Driesboy** [comment]
nederlands mag ook hoor

**Comment by Sandertv** [comment]
:P

**Pull request closed without merging**
